// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwpkgzyjdnptidlxpyzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cGtnenlqZG5wdGlkbHhweXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzEyMzYsImV4cCI6MjA2ODE0NzIzNn0.DsA1i8tAVcAE9ydMma-K9mlaPxLaPm9e965jyZYxrnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});